name: Generate and Publish Docs

on:
  push:
    branches:
      - main
      - 35_fix_docs

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Generate TypeDocs
        run: npm run docs && ls -a docs

      - name: Archive artifact
        shell: sh
        run: |
          echo ::group::Archive artifact
          tar \
            --dereference --hard-dereference \
            --create \
            --file "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            -C ./docs/ .  # Include all files in the 'docs' directory
          echo ::endgroup::
      - name: Upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: artifact.tar
          retention-days: "1"
          if-no-files-found: error
