name: Generate and Publish Docs

on:
  push:
    branches:
      - main
      - 35_fix_docs

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment: github-pages
    # Deploy to the github-pages environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

      - name: Setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install

      - name: Generate TypeDocs
        run: npm run docs && ls -a docs

      - name: Upload TypeDocs as GitHub Pages Artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
