name: Publish to NPM as Beta

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Ensures all history is fetched for all branches and tags

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 21.x
        registry-url: 'https://registry.npmjs.org/'

    - name: Install dependencies
      run: yarn

    # Set version from PR title or description. Example PR title: "Add new feature version:minor"
    - name: Set Version
      run: |
        VERSION_KEYWORD=$(echo '${{ github.event.pull_request.title }}' | grep -oP '(?<=version:)(major|minor|patch)')
        if [ ! -z "$VERSION_KEYWORD" ]; then
          npm version pre$VERSION_KEYWORD --preid alpha --no-git-tag-version
        else
          echo "No version keyword found in PR title"
          exit 1
        fi

    - name: Build
      run: npm run build

    - name: Publish to NPM
      run: npm publish --tag beta
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
